---
title: "Project roadmap"
site: workflowr::wflow_site
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "Yong See Foo"
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

To record progress, and to organise things to do (in italics).

# Model
- Explore possible model specifications for sparse factor analysis in existing literature.
- Specify the distributions of the sparse factor model. See Section 1 of the [derivation](assets/derivation.pdf).

# MCMC
- Derive collapsed Gibbs sampling, where the regulatory weights $\mathbf{L}$ are marginalised out of the conditional distribution of the connectivity matrix $\mathbf{Z}$. See Section 2.1 of the derivation.
- Implement collapsed Gibbs sampling.
- Apply a relabelling algorithm to address label/sign-switching (model non-identifiability).
- *Use Empirical Bayes to estimate the sparsity hyperparameters $\boldsymbol{\pi}$.*

# Variational inference
- Derive the coordinate ascent approach for a mean-field approximation. See Section 3 of the derivation.
- Implement the coordinate ascent approach.
- *Investigate whether variational approximations are inadequate in the case of multiple modes in close proximity.*
- *If necessary, address the issue of multiple modes via a Monte Carlo approach to variational inference combined with a relabelling algorithm.*

# Evaluation
- *Calculate the predictive accuracy and mean probability of the connectivity matrix $\mathbf{Z}$ under the marginal posterior distribution.*
- *Relabel inference results to match with the true (simulated) parameters.*
- *Calculate the RRMSE of the parameter estimates of $\mathbf{L}$, $\mathbf{F}$, and $\mathbf{LF}$.*
- *Investigate the performance of both methods on real data.*

# Presentation
(due 10 Feb)

# Poster
(due 14 Feb)

# Report
(due 28 Feb)

# Blog post
(due 28 Feb)
