# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cavi <- function(ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, max_iter = 10L, seed = -1L, debug = FALSE) {
    .Call(`_sparsefactor_cavi`, ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, max_iter, seed, debug)
}

gibbs <- function(n_iter, ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, sign_switch = TRUE, label_switch = TRUE, seed = -1L) {
    .Call(`_sparsefactor_gibbs`, n_iter, ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, sign_switch, label_switch, seed)
}

#' @title myFunction
#' @description
#' Modify a string in Rcpp.
#' @name myFunction
#' @param x a vector of strings
#' @examples
#' myFunction(x=c('Hello', "C++", 'header', 'files'))
#'
#' @export
myFunction <- function(x) {
    .Call(`_sparsefactor_myFunction`, x)
}

relabel <- function(samples, sign_switch = TRUE, label_switch = TRUE, print_action = FALSE, print_cost = FALSE, to_clone = TRUE) {
    .Call(`_sparsefactor_relabel`, samples, sign_switch, label_switch, print_action, print_cost, to_clone)
}

