# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbs <- function(n_iter, ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, sign_switch = TRUE, label_switch = TRUE, seed = -1L, debug = FALSE) {
    .Call(`_sparsefactor_gibbs`, n_iter, ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, sign_switch, label_switch, seed, debug)
}

#' @title myFunction
#' @description
#' Modify a string in Rcpp.
#' @name myFunction
#' @param x a vector of strings
#' @examples
#' myFunction(x=c('Hello', "C++", 'header', 'files'))
#'
#' @export
myFunction <- function(x) {
    .Call(`_sparsefactor_myFunction`, x)
}

rcpp_hello_world <- function() {
    .Call(`_sparsefactor_rcpp_hello_world`)
}

relabel <- function(samples, sign_switch, label_switch, to_clone = TRUE) {
    .Call(`_sparsefactor_relabel`, samples, sign_switch, label_switch, to_clone)
}

