# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' VI entry point, handles NAs
#' `check` is how often elbo is calculated and checked for convergence as full elbo calculation is expensive
#' `save` is how often the parameters are saved
#' algorithm terminates if max difference of z between two iterations is below `tol_z`
#' `tol_z` of 0 means the above is effectively not checked for'
#' @export
cavi <- function(ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, check = 100L, save = 0L, max_iter = 5000L, tol_elbo = 1e-14, tol_z = 0, seed = -1L) {
    .Call('_sparsefactor_cavi', PACKAGE = 'sparsefactor', ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, check, save, max_iter, tol_elbo, tol_z, seed)
}

#' VI entry point, assumes no NAs
#' unlike the other two CAVIs, the variational parameters of variance of F is not one for each F-entry
#' instead, dependency is estimated, so a covriance matrix is stored as a variational parameter (same for each column)
#' `check` is how often elbo is calculated and checked for convergence as full elbo calculation is expensive
#' `save` is how often the parameters are saved
#' algorithm terminates if max difference of z between two iterations is below `tol_z`
#' `tol_z` of 0 means the above is effectively not checked for
#' @export
cavi_fdep <- function(ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, check = 100L, save = 0L, max_iter = 5000L, tol_elbo = 1e-14, tol_z = 0, seed = -1L) {
    .Call('_sparsefactor_cavi_fdep', PACKAGE = 'sparsefactor', ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, check, save, max_iter, tol_elbo, tol_z, seed)
}

#' VI entry point, assumes no NAs present
#' `check` is how often elbo is calculated and checked for convergence as full elbo calculation is expensive
#' `save` is how often the parameters are saved
#' algorithm terminates if max difference of z between two iterations is below `tol_z`
#' `tol_z` of 0 means the above is effectively not checked for
#' @export
cavi_full <- function(ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, check = 100L, save = 0L, max_iter = 5000L, tol_elbo = 1e-14, tol_z = 0, seed = -1L) {
    .Call('_sparsefactor_cavi_full', PACKAGE = 'sparsefactor', ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, check, save, max_iter, tol_elbo, tol_z, seed)
}

#' entry point for MCMC, handles NAs
#' @export
gibbs <- function(n_samples, ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, burn_in = 0L, thin = 1L, seed = -1L) {
    .Call('_sparsefactor_gibbs', PACKAGE = 'sparsefactor', n_samples, ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, burn_in, thin, seed)
}

#' @export
relabel <- function(samples, tol = 1e-8, print_action = FALSE, print_cost = FALSE, to_clone = TRUE) {
    .Call('_sparsefactor_relabel', PACKAGE = 'sparsefactor', samples, tol, print_action, print_cost, to_clone)
}

#' @export
relabel_truth <- function(truth, fmeans, fsigs, print_mat = FALSE) {
    .Call('_sparsefactor_relabel_truth', PACKAGE = 'sparsefactor', truth, fmeans, fsigs, print_mat)
}

