# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cavi <- function(ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, check = 100L, save = 0L, max_iter = 5000L, tol_elbo = 1e-14, tol_z = 0, seed = -1L) {
    .Call(`_sparsefactor_cavi`, ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, check, save, max_iter, tol_elbo, tol_z, seed)
}

cavi_fdep <- function(ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, check = 100L, save = 0L, max_iter = 5000L, tol_elbo = 1e-14, tol_z = 0, seed = -1L) {
    .Call(`_sparsefactor_cavi_fdep`, ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, check, save, max_iter, tol_elbo, tol_z, seed)
}

cavi_full <- function(ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, check = 100L, save = 0L, max_iter = 5000L, tol_elbo = 1e-14, tol_z = 0, seed = -1L) {
    .Call(`_sparsefactor_cavi_full`, ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, check, save, max_iter, tol_elbo, tol_z, seed)
}

gibbs <- function(n_samples, ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, burn_in = 0L, thin = 1L, seed = -1L) {
    .Call(`_sparsefactor_gibbs`, n_samples, ymat, pivec, ptaushape, ptaurate, palphashape, palpharate, burn_in, thin, seed)
}

relabel <- function(samples, tol = 1e-8, print_action = FALSE, print_cost = FALSE, to_clone = TRUE) {
    .Call(`_sparsefactor_relabel`, samples, tol, print_action, print_cost, to_clone)
}

relabel_truth <- function(truth, fmeans, fsigs, print_mat = FALSE) {
    .Call(`_sparsefactor_relabel_truth`, truth, fmeans, fsigs, print_mat)
}

